In [8]:
from datetime import datetime, timedelta
from collections import deque, defaultdict, Counter
import matplotlib.pyplot as plt

from aqi_pkg.db import get_session
from aqi_pkg.filters import *
from aqi_pkg.ml.clustering import *

import polars as pl

In [9]:
def get_all_data() -> pl.DataFrame:
    filter = Filter()
    loader = DataLoader(filter)

    data = loader.get_df()
    return data

In [10]:
start_time = datetime.now()
session = get_session()
plt.style.use("tableau-colorblind10")
try:
    df = get_all_data()
finally:
    session.close()
    print("Session closed.")
end_time = datetime.now()
print(f"Execution time: {end_time - start_time}")

Session closed.
Execution time: 0:00:12.086316

In [11]:
df.head()

shape: (5, 21)
┌───────────┬───────────┬───────────┬──────────────┬───┬───────────┬──────┬──────────┬──────────┐
│ scrape_id ┆ lat       ┆ lon       ┆ locationId   ┆ … ┆ H_PERCENT ┆ T_C  ┆ TVOC_PPM ┆ Noise_DB │
│ ---       ┆ ---       ┆ ---       ┆ ---          ┆   ┆ ---       ┆ ---  ┆ ---      ┆ ---      │
│ i64       ┆ f64       ┆ f64       ┆ str          ┆   ┆ f64       ┆ f64  ┆ f64      ┆ f64      │
╞═══════════╪═══════════╪═══════════╪══════════════╪═══╪═══════════╪══════╪══════════╪══════════╡
│ 362829    ┆ 24.0299   ┆ 73.0463   ┆ VIR11283     ┆ … ┆ 28.0      ┆ 23.0 ┆ null     ┆ null     │
│ 18798114  ┆ 28.666833 ┆ 77.119268 ┆ 2555         ┆ … ┆ 77.0      ┆ 18.0 ┆ null     ┆ null     │
│ 9030653   ┆ 26.1541   ┆ 81.8114   ┆ PLLODA000554 ┆ … ┆ 43.0      ┆ 11.0 ┆ null     ┆ null     │
│ 7392322   ┆ 28.7091   ┆ 76.8182   ┆ PLLODA000203 ┆ … ┆ 63.0      ┆ 15.0 ┆ null     ┆ null     │
│ 6518437   ┆ 27.9977   ┆ 73.3486   ┆ PLLODA000447 ┆ … ┆ 18.0      ┆ 20.0 ┆ null     ┆ null     │
└───────────┴───────────┴───────────┴──────────────┴───┴───────────┴──────┴──────────┴──────────┘

In [19]:
df.group_by("country").len().sort("len", descending=True)

shape: (19, 2)
┌──────────────┬──────────┐
│ country      ┆ len      │
│ ---          ┆ ---      │
│ str          ┆ u32      │
╞══════════════╪══════════╡
│ India        ┆ 15667005 │
│ Nepal        ┆ 470721   │
│ Pakistan     ┆ 40197    │
│ Thailand     ┆ 999      │
│ China        ┆ 264      │
│ …            ┆ …        │
│ Bangladesh   ┆ 12       │
│ Turkmenistan ┆ 6        │
│ Burma        ┆ 3        │
│ Myanmar      ┆ 3        │
│ Afghanistan  ┆ 3        │
└──────────────┴──────────┘

# Investigating 3

In [12]:
counts = df.group_by("locationId").len()
print(counts.describe())

shape: (9, 3)
┌────────────┬────────────┬─────────────┐
│ statistic  ┆ locationId ┆ len         │
│ ---        ┆ ---        ┆ ---         │
│ str        ┆ str        ┆ f64         │
╞════════════╪════════════╪═════════════╡
│ count      ┆ 3492       ┆ 3492.0      │
│ null_count ┆ 0          ┆ 0.0         │
│ mean       ┆ null       ┆ 4633.408076 │
│ std        ┆ null       ┆ 5352.182666 │
│ min        ┆ -100165    ┆ 1.0         │
│ 25%        ┆ null       ┆ 3.0         │
│ 50%        ┆ null       ┆ 2398.0      │
│ 75%        ┆ null       ┆ 8487.0      │
│ max        ┆ VIR9985    ┆ 13380.0     │
└────────────┴────────────┴─────────────┘

In [13]:
df_three = counts.filter(pl.col("len") == 3)

In [17]:
df.filter(pl.col("locationId").is_in(df_three["locationId"].implode())).group_by("country").len().sort("len", descending=True)

shape: (19, 2)
┌──────────────┬──────┐
│ country      ┆ len  │
│ ---          ┆ ---  │
│ str          ┆ u32  │
╞══════════════╪══════╡
│ India        ┆ 1839 │
│ Thailand     ┆ 999  │
│ China        ┆ 264  │
│ Kyrgyzstan   ┆ 219  │
│ Iran         ┆ 120  │
│ …            ┆ …    │
│ Nepal        ┆ 9    │
│ Turkmenistan ┆ 6    │
│ Myanmar      ┆ 3    │
│ Burma        ┆ 3    │
│ Afghanistan  ┆ 3    │
└──────────────┴──────┘

In [ ]:
df_threesremoved = df.filter(~pl.col("locationId").is_in(df_three["locationId"].implode()))
df_threesremoved.group_by("country").len().sort("len", descending=True)