In [1]:
from datetime import datetime, timedelta
from collections import deque, defaultdict, Counter
import matplotlib.pyplot as plt

from aqi_pkg.db import get_session
from aqi_pkg.filters import *
from aqi_pkg.ml.clustering import *

import polars as pl

In [2]:
def get_all_data() -> pl.DataFrame:
    filter = Filter()
    loader = DataLoader(filter)

    data = loader.get_df()
    return data

In [3]:
start_time = datetime.now()
session = get_session()
plt.style.use("tableau-colorblind10")
try:
    df = get_all_data()
finally:
    session.close()
    print("Session closed.")
end_time = datetime.now()
print(f"Execution time: {end_time - start_time}")

Session closed.
Execution time: 0:00:12.336937

In [7]:
df.head()

shape: (5, 21)
┌───────────┬───────────┬──────────┬──────────────┬───┬───────────┬──────┬──────────┬──────────┐
│ scrape_id ┆ lat       ┆ lon      ┆ locationId   ┆ … ┆ H_PERCENT ┆ T_C  ┆ TVOC_PPM ┆ Noise_DB │
│ ---       ┆ ---       ┆ ---      ┆ ---          ┆   ┆ ---       ┆ ---  ┆ ---      ┆ ---      │
│ i64       ┆ f64       ┆ f64      ┆ str          ┆   ┆ f64       ┆ f64  ┆ f64      ┆ f64      │
╞═══════════╪═══════════╪══════════╪══════════════╪═══╪═══════════╪══════╪══════════╪══════════╡
│ 9769562   ┆ 28.5474   ┆ 77.2107  ┆ E4B063384860 ┆ … ┆ 35.0      ┆ 20.0 ┆ 9.93     ┆ 55.0     │
│ 765338    ┆ 28.4164   ┆ 77.0387  ┆ PLLODA000327 ┆ … ┆ 72.0      ┆ 15.0 ┆ null     ┆ null     │
│ 2326315   ┆ 27.6531   ┆ 85.3023  ┆ 10495        ┆ … ┆ 35.0      ┆ 21.0 ┆ null     ┆ null     │
│ 15762233  ┆ 31.328908 ┆ 75.57264 ┆ 11299        ┆ … ┆ 67.0      ┆ 10.0 ┆ null     ┆ null     │
│ 13063548  ┆ 30.6714   ┆ 76.1076  ┆ PLLODA000193 ┆ … ┆ 47.0      ┆ 20.0 ┆ null     ┆ null     │
└───────────┴───────────┴──────────┴──────────────┴───┴───────────┴──────┴──────────┴──────────┘

In [11]:
counts = df.group_by("locationId").len()
print(counts.describe())

shape: (9, 3)
┌────────────┬────────────┬─────────────┐
│ statistic  ┆ locationId ┆ len         │
│ ---        ┆ ---        ┆ ---         │
│ str        ┆ str        ┆ f64         │
╞════════════╪════════════╪═════════════╡
│ count      ┆ 3492       ┆ 3492.0      │
│ null_count ┆ 0          ┆ 0.0         │
│ mean       ┆ null       ┆ 4632.934422 │
│ std        ┆ null       ┆ 5351.79423  │
│ min        ┆ -100165    ┆ 1.0         │
│ 25%        ┆ null       ┆ 3.0         │
│ 50%        ┆ null       ┆ 2397.0      │
│ 75%        ┆ null       ┆ 8486.0      │
│ max        ┆ VIR9985    ┆ 13379.0     │
└────────────┴────────────┴─────────────┘

In [19]:
df_three = counts.filter(pl.col("len") == 3)

In [ ]:
df.filter(pl.col("locationId") == "1419")

shape: (5, 2)
┌────────────┬─────┐
│ locationId ┆ len │
│ ---        ┆ --- │
│ str        ┆ u32 │
╞════════════╪═════╡
│ 1419       ┆ 3   │
│ VIR8572    ┆ 3   │
│ -104422    ┆ 3   │
│ 8033       ┆ 3   │
│ -361882    ┆ 3   │
└────────────┴─────┘